import { Poppins } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import { Box } from "@mui/material";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "../styles/globals.css";
import { AuthProvider } from "@/context/AuthContext";
const poppins = Poppins({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};
export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={poppins.className}
				style={{ backgroundColor: "#F5F5F5" }}
			>
				<AuthProvider>
					<ToastContainer
						position="top-center"
						autoClose={2000}
						hideProgressBar={false}
						newestOnTop={false}
						closeOnClick
						rtl={false}
						pauseOnFocusLoss
						draggable
						pauseOnHover
						theme="dark"
					/>
					<Box
						style={{
							display: "flex",
							justifyContent: "space-between",
							flexDirection: "column",
							height: "100%",
						}}
					>
						<Nav />
						{children}
						<Footer />
					</Box>
				</AuthProvider>
			</body>
		</html>
	);
}
